### ISSUE TITLE
Button disabled and greyed out on protected profiles

### ISSUE THREAD

**Issue by Xiazee** [Flkalas/TwitterMediaAssist#38] opened 2024-05-17 17:50 UTC
Since the share and retweet buttons are also disabled it appears the download button inherits this.

If `disabled=""` is removed the button becomes functional, but still needs to fix colors and animations.

**Comment by TOOMANYENEMIES64** [comment] 2024-05-19 02:37
Having the same issue but with no functionality. Previously was greyed out but function remained

**Comment by Flkalas** [comment] 2024-05-23 11:36
This is a duplicate of #41. I will handle it there.

**Closed by Flkalas** 2024-05-23 11:36 UTC
